### ISSUE TITLE
Fresh install: Can't perform a full/incremental backup

### ISSUE THREAD

**Issue by rvargasg** [lucascbeyeler/zmbackup#100]
**ISSUE TYPE**
- Bug Report

**ENVIRONMENT VERSION**
- Zmbackup Version: 1.2.2
- Zimbra Version: 8.8.8
- Linux Distribution & Version: Ubuntu 16.04.4 LTS

**SUMMARY**

After installing, nothing happends. It's says "nothing to do"

**STEPS TO REPRODUCE**
After a clean installation I try to run both the full and incremental copy with the command **zmbackup -f** or **zmbackup -i**.

I've tried to do a **--force**, but nothing happends. But if I make a individual backup is made correctly.

**ACTUAL RESULTS**
zmbackup -f
WARN: account1@email.com already has backup today. Nothing to do.
WARN: account2@email.com already has backup today. Nothing to do.
WARN: account3@email.com already has backup today. Nothing to do.
Nothing to do. Closing...

zmbackup -i
WARN: account1@email.com already has backup today. Nothing to do.
WARN: account2@email.com already has backup today. Nothing to do.
WARN: account3@email.com already has backup today. Nothing to do.
Nothing to do. Closing...

**Comment by tdemeter** [comment]
I have  exactly same problem. It was fresh install. Before 1.2, I do use this backup,but from 1.2.2 does not.
What can I do?

**Comment by lucascbeyeler** [comment]
@tdemeter,

The release 1.2.2 does not exist yet... If you see there is a tag saying "Unstable" in red in the begining of the site :)

The latest stable version is 1.2.1.

Regards,
Lucas Costa Beyeler

**Comment by rvargasg** [comment]
![zmbackup_122](https://user-images.githubusercontent.com/39514484/42799671-fa71e664-8998-11e8-9e38-16892584400e.PNG)

Sorrry, but that's the version I can see in logs and README inside of the installation folder.

**Comment by rvargasg** [comment]
I'm sorry, but I didn't realize it. Thank you!
