### ISSUE TITLE
Restore command raise a exception with mailbox bigger than 2GB

### ISSUE THREAD

**Issue by ibirisol** [lucascbeyeler/zmbackup#107]
##### ISSUE TYPE
- Bug Report

##### ENVIRONMENT VERSION
- Zmbackup Version: 1.2.2
- Zimbra Version: 8.8.8.GA.2009
- Linux Distribution & Version: Ubuntu 16.04.4 LTS

##### SUMMARY

When I try to restore a mailbox bigger than 2GB with zmbackup the httpie raises:

```
http: error: OverflowError: string longer than 2147483647 bytes
```

I found a similar bug in [1-2]. A workaround made by [1] changed httpie by curl.

[1] https://gitlab.esss.lu.se/ics-infrastructure/ics-shared-gitlab-ci-functions/commit/bb283ec7003f8380756141059c8e9b06c7903443?view=parallel
[2] https://github.com/requests/requests/issues/2717

##### STEPS TO REPRODUCE
```
$ zmbackup --restore <session> <account>
```

##### ACTUAL RESULTS
```
http: error: OverflowError: string longer than 2147483647 bytes
```

**Comment by ibirisol** [comment]
In pull request #108 I send a modification suggestion.

**Comment by ibirisol** [comment]
Hi Lucas, how could I help you with this bug? Are You with a tool name in your mind? Or you will fix HTTPie?

**Comment by vladT0** [comment]
@ibirisol : Hi ! I have made myself changes in scripts. Now zmbackup tool is working with "curl" and I have no this 2GB limitation. The big second advantage, tool is working for old ubuntu versions, such as 12.04 (where httpie was not presented ) and I have managed to backup mail server on it and restore to latest version. I can share my changes.

**Comment by cleitonrnovotni** [comment]
Hello, good night, could you share your code with me? I am encountering the same problem when trying to restore mailbox backups here, thanks.

**Comment by vladT0** [comment]
Hi !
File ParallelAction.sh:
```
function mailbox_restore()
{
  ERR=$(curl --insecure -X POST -u "$ADMINUSER:$ADMINPASS" -T "$WORKDIR/$1/$2.tgz" "$WEBPROTO://$MAILHOST:7071/home/$2/?fmt=tgz")
  if ! [[ $? -eq 0 ]]; then
    printf "Error during the restore process for account $2. Error message below:"
    printf "$2: $ERR"
  elif [[ "$ERR"  == *"No such file or directory" ]]; then
    printf "Account $2 has nothing to restore - skipping..."
  fi
}
```
File RestoreAction.sh:
```
function restore_main_mailbox()
{
  if [[ $SESSION_TYPE == 'TXT' ]]; then
    SESSION=$(egrep ": $1 started" $WORKDIR/sessions.txt | egrep 'started' | \
                  awk '{print $2}' | sort | uniq)
  elif [[ $SESSION_TYPE == "SQLITE3" ]]; then
    SESSION=$(sqlite3 $WORKDIR/sessions.sqlite3 "select * from backup_session where sessionID='$1'")
  fi
  if ! [ -z "$SESSION" ]; then
    printf "Restore mail process with session $1 started at $(date)"
    if [[ ! -z $3 && $2 == *"@"* ]]; then
      ERR=$(curl --insecure -X POST -u "$ADMINUSER:$ADMINPASS" -T "$WORKDIR/$1/$2.tgz" "$WEBPROTO://$MAILHOST:7071/home/$3/?fmt=tgz")
      if [[ $? -eq 0 ]]; then
        printf "Account $2 restored with success"
      else
        printf "Error during the restore process for account $2. Error message below:"
        printf $ERR
      fi
    else
      build_listRST $1 $2
      cat $TEMPACCOUNT | parallel --jobs $MAX_PARALLEL_PROCESS \
               "mailbox_restore $1 {}"
    fi
    printf "\nRestore mail process with session $1 completed at $(date)\n"
  else
    echo "Nothing to do. Closing..."
    rm -rf $PID
  fi
}

```

**Comment by vladT0** [comment]
Hi ! Sorry for the strange formatting inside tag code.
File ParallelAction.sh:
`function mailbox_restore()
{
  ERR=$(curl --insecure -X POST -u "$ADMINUSER:$ADMINPASS" -T "$WORKDIR/$1/$2.tgz" "$WEBPROTO://$MAILHOST:7071/home/$2/?fmt=tgz")
  if ! [[ $? -eq 0 ]]; then
    printf "Error during the restore process for account $2. Error message below:"
    printf "$2: $ERR"
  elif [[ "$ERR"  == *"No such file or directory" ]]; then
    printf "Account $2 has nothing to restore - skipping..."
  fi
}`
File RestoreAction.sh:
`function restore_main_mailbox()
{
  if [[ $SESSION_TYPE == 'TXT' ]]; then
    SESSION=$(egrep ": $1 started" $WORKDIR/sessions.txt | egrep 'started' | \
                  awk '{print $2}' | sort | uniq)
  elif [[ $SESSION_TYPE == "SQLITE3" ]]; then
    SESSION=$(sqlite3 $WORKDIR/sessions.sqlite3 "select * from backup_session where sessionID='$1'")
  fi
  if ! [ -z "$SESSION" ]; then
    printf "Restore mail process with session $1 started at $(date)"
    if [[ ! -z $3 && $2 == *"@"* ]]; then
      ERR=$(curl --insecure -X POST -u "$ADMINUSER:$ADMINPASS" -T "$WORKDIR/$1/$2.tgz" "$WEBPROTO://$MAILHOST:7071/home/$3/?fmt=tgz")
      if [[ $? -eq 0 ]]; then
        printf "Account $2 restored with success"
      else
        printf "Error during the restore process for account $2. Error message below:"
        printf $ERR
      fi
    else
      build_listRST $1 $2
      cat $TEMPACCOUNT | parallel --jobs $MAX_PARALLEL_PROCESS \
               "mailbox_restore $1 {}"
    fi
    printf "\nRestore mail process with session $1 completed at $(date)\n"
  else
    echo "Nothing to do. Closing..."
    rm -rf $PID
  fi
}`
