### ISSUE TITLE
Error with log file and FULL BACKUP

### ISSUE THREAD

**Issue by luisely** [lucascbeyeler/zmbackup#109]
##### ISSUE TYPE
- Question

##### ENVIRONMENT VERSION
- Zmbackup Version: 1.2.1
- Zimbra Version: 8.7.11_GA_1854.FOSS
- Linux Distribution & Version: CentOS release 6.9

##### SUMMARY
1. The log file is never created after the backup is finished, the path is correct in the CONF
2. I want to do full backup every day, I set it up on CRON to run every day, but every day the full backup is different sizes, accounts that were to be of 7GB are with 200MB. I try to open this backup and it says it's corrupted.

```
00 19  * * 1-5     zimbra  zmbackup -f
```

##### STEPS TO REPRODUCE
```
1. Execute backup with zmbackup -f, after concluding, there is no log file.
2. It simply does not perform full backup every day, I do not know why.
```
We used zmbkpose previously and since it was too slow to conclude the backup, we decided to change the program.

Every day we perform a full backup with zmbkpose, but zmbackup is not working.

**Comment by ananiasfilho** [comment]
We have fixed and it will be available in next hours.
@luisely  - You can fix it using our FORK while @lucascbeyeler accept merge/pull request.
https://github.com/ananiasfilho/zmbackup

**Comment by lucascbeyeler** [comment]
Hello @luisely,

Could you try again? I included all the fixes proposed by @ananiasfilho inside the project.

Regards,
Lucas Costa Beyeler
