### ISSUE TITLE
Restoring all accounts in one moment.

### ISSUE THREAD

**Issue by stasstryukov** [lucascbeyeler/zmbackup#117]
Hi all.
Maybe I'm so stuped, but can I restore all mails in one domain with one command?
Now i can restore one mailbox per entered command like zmbackup -r -m -d full-20181008121906 mail@domain.com
But if i want to restore all mailboxes in one time, what I must to use?
Tnx.

**Comment by lucascbeyeler** [comment]
There is no option for now - will include in Waddles
