### ISSUE TITLE
Erro Memory httpie - restore

### ISSUE THREAD

**Issue by thytetgc** [lucascbeyeler/zmbackup#118]
##### ISSUE TYPE
- Bug Report
- Question

##### ENVIRONMENT VERSION
- Zmbackup Version: 1.2.3
- Zimbra Version: 8.8.9
- Linux Distribution & Version: Ubuntu 16

##### SUMMARY
Ao rodar o restore full, ocorrem erros no httpie. Ele esta jogando as mensagens para memoria ram, fazendo com que gerem erros do tipo

##### STEPS TO REPRODUCE
```
zmbackup -r full-xxxxxxxxxxx
```

##### ACTUAL RESULTS
```
http: error: MemoryError: Error during the restore process for account user@domain.com.
```

**Comment by lucascbeyeler** [comment]
fixed - dropped httpie in favor of curl
