### ISSUE TITLE
Erro SSL - restore

### ISSUE THREAD

**Issue by thytetgc** [lucascbeyeler/zmbackup#119]
##### ISSUE TYPE
- Bug Report
- Question

##### ENVIRONMENT VERSION
- Zmbackup Version: 1.2.3
- Zimbra Version: 8.8.9
- Linux Distribution & Version: Ubuntu 16

##### SUMMARY
Ao fazer o restore usando Admin na porta 443 (SSL) é gerado um erro, e não faz a importação.

##### STEPS TO REPRODUCE
```
zmbackup -r full-xxxxxxxxxxxx
```

##### ACTUAL RESULTS
```
Error during the restore process for account user@domain.com......... Unverified HTTPS request is being made. Adding certificate verification is strongly advised
```

**Comment by farazsiddiqui2010** [comment]
Is there any update on this, i am also facing same issue.

**Comment by kharinva** [comment]
Hi guys,
I had the same issue.
You should set your zmbackup@xxxxx.com account as a global admin.

**Comment by lucascbeyeler** [comment]
Fixed.
