### ISSUE TITLE
Mudar Sequencia de restore full

### ISSUE THREAD

**Issue by thytetgc** [lucascbeyeler/zmbackup#120]
##### ISSUE TYPE
- Feature Idea
- Enhancement

##### ENVIRONMENT VERSION
- Zmbackup Version: 1.2.3
- Zimbra Version: 8.8.9
- Linux Distribution & Version: Ubuntu 16

##### SUMMARY
Ao fazer restauração completa ele restaura a base primeiro, em sequencia os usuários, mailbox, listas e alias. Se um erro ocorrer na restauração da mailbox, as listas e alias não são restauradas.

A melhor sequencia seria:

1. Restore ldap
2. Restore alias
3. Restore listas
4. Restore mailbox

##### STEPS TO REPRODUCE
```
zmbackup -f fulll-xxxxxxxxxx
```

**Comment by lucascbeyeler** [comment]
Fixed - Zmbackup already restoring in the required order.
