### ISSUE TITLE
Erro Restore Alias

### ISSUE THREAD

**Issue by thytetgc** [lucascbeyeler/zmbackup#121]
##### ISSUE TYPE
- Bug Report
- Question

##### ENVIRONMENT VERSION
- Zmbackup Version: 1.2.3
- Zimbra Version: 8.8.9
- Linux Distribution & Version: Ubuntu 16

##### SUMMARY
Ao fazer o restore do Alias, ele cria os Alias, porem não aponta para os devidos e-mails.

##### STEPS TO REPRODUCE
```
zmbackup -r alias-xxxxxxxxx
```

##### ACTUAL RESULTS
```

```

**Comment by lucascbeyeler** [comment]
Closing the issue - cant reproduce with 1.2.5
