### ISSUE TITLE
User/password is visible during backup

### ISSUE THREAD

**Issue by rogeriobastos** [lucascbeyeler/zmbackup#123]
##### ISSUE TYPE
- Bug Report

##### ENVIRONMENT VERSION
- Zmbackup Version: 1.2.1
- Zimbra Version: 8.8.10
- Linux Distribution & Version: Ubuntu 16.04.4 LTS

##### SUMMARY
While backup is being performed is possible to see user and password used to do backup.

##### STEPS TO REPRODUCE
- Run a backup
- List running process and filter by the HTTP client (in my case wget)

**Comment by lucascbeyeler** [comment]
Hi Rogerio,

There is no solution for that and I do not consider this as a security problem. If you can see the password by using grep you already have access inside the host to do whatever you want.
