### ISSUE TITLE
Schedule Backup Time via zmbackup

### ISSUE THREAD

**Issue by farazsiddiqui2010** [lucascbeyeler/zmbackup#125]
ISSUE TYPE
 Question

 ENVIRONMENT VERSION
- Zmbackup Version: 1.2.3
- Zimbra Version: 8.8.5
- Linux Distribution & Version: Centos 7.5

SUMMARY
How can we schedule backups with the help of zmbackup?
zmbackup takes daily incremental backup at 01:30 AM EST and full backup weekly on sunday at 1:30AM, can we change this weekly backup to saturday instead of sunday?

**Comment by enribar** [comment]
Hi, take a look at #129
