### ISSUE TITLE
List session -> not meaningful Description field

### ISSUE THREAD

**Issue by kladiv** [lucascbeyeler/zmbackup#126]
Hello,
nice project!
I suggest to enhance the "list" command when we make backups of some specific objects (e.g. domains, accounts).
In my opinion there's no a correct display of the _Description_ field of list command. It's a simple "Full Account" but it should explain what that backup session refers.

Thank you!

##### ISSUE TYPE
- Enhancement

##### ENVIRONMENT VERSION
- Zmbackup Version: 1.3.2
- Zimbra Version: 8.5.0.GA.3042
- Linux Distribution & Version: Ubuntu 14.04 LTS

##### STEPS TO REPRODUCE
```
zimbra@mail:~$ zmbackup -f -d example.com
Domain example.com found! - Inserting inside the backup queue.
WARN: galsync@example.com found inside blacklist - Nothing to do.
Backup session full-20190119222050 started on Sat Jan 19 22:20:50 +08 2019
Backup session full-20190119222050 finished on Sat Jan 19 22:21:01 +08 2019
```

##### ACTUAL RESULTS
```
+---------------------------+--------------+--------------+----------+----------------------------+
|       Session Name        |    Start     |    Ending    |   Size   |        Description         |
+---------------------------+--------------+--------------+----------+----------------------------+
| full-20190119222050       |  01/19/2019  |  01/19/2019  | 34M      | Full Account               |
+---------------------------+--------------+--------------+----------+----------------------------+
```

**Comment by ananiasfilho** [comment]
Hello @kladiv just to be clear.
If you define domain on backup process, you will need see into description something like: "Full Accounts backup to domain example.com" 
if yes, i will try start make this on next days.
if not, please, explain better.
