### ISSUE TITLE
A warning, this backup tool may not be reliable

### ISSUE THREAD

**Issue by ghost** [lucascbeyeler/zmbackup#127]
Hello All,

It seems this backup tool relies on exporting mailboxes using the Zimbra REST API

https://github.com/Zmbackup/zmbackup/blob/1.2-version/project/lib/bash/ParallelAction.sh#L48

This has been known to be unreliable, and may cause corrupted backups.

https://bugzilla.zimbra.com/show_bug.cgi?id=101760
https://bugzilla.zimbra.com/show_bug.cgi?id=86347

The tgz option shoud be fixed before one can use backup tools like the one in this repo. This has been confirmed by Zimbra staff in the bugzilla reports.

Barry

**Comment by enribar** [comment]
> Hello All,
> 
> It seems this backup tool relies on exporting mailboxes using the Zimbra REST API
> 
> https://github.com/Zmbackup/zmbackup/blob/1.2-version/project/lib/bash/ParallelAction.sh#L48
> 
> This has been known to be unreliable, and may cause corrupted backups.
> 
> https://bugzilla.zimbra.com/show_bug.cgi?id=101760
> https://bugzilla.zimbra.com/show_bug.cgi?id=86347
> 
> The tgz option shoud be fixed before one can use backup tools like the one in this repo. This has been confirmed by Zimbra staff in the bugzilla reports.
> 
> Barry

Hello Barry,
do you know if there are any free backup alternatives other than using Zimbra REST APIs?

**Comment by ghost** [comment]
Unfortunately I do not think there is one.

Someone should get dirty hands and fix the parts in Zimbra that break the export, I can imagine pathing the java so that it throws an account to a folder instead of a tgz. From there we can have a different process make the tgz.

Then we could debug the import process, I am not 100% sure how broken that is.

So the export, is I think fixable. It just needs someone to put the time in.

**Comment by vadonka** [comment]
The project is abandoned? It seems to. No words from the dev?

**Comment by ghost** [comment]
looks like so

**Comment by vadonka** [comment]
I guess i need to rewrite the backup/restore part to use the zmmailbox api and not the wget/curl method.

**Comment by ananiasfilho** [comment]
Hello guys! The project is stoped but not die! Lucas move from Brazil to Ireland and have a lot of things to do before back to zmbackup development. The version 2 will came this year. Im working hard on new zimbra 2 all re-write and using python3.
I will dedicate this week to check issues and feedback all of you. Feel free to fork project and send Pull requests.

**Comment by lucascbeyeler** [comment]
Hi,

Good to know that Zimbra is breaking the backups for no reason. The only solution I can see for this would be reverse engineer Zimbra to generate the tgz files by ourselves. I'm moving this idea to Waddles as I will continue developing Zmbackup as a Python solution.
