### ISSUE TITLE
Upgrade procedure?

### ISSUE THREAD

**Issue by enribar** [lucascbeyeler/zmbackup#128]
Hi,
today I upgraded my installation from version 1.2.2 to 1.2.3 . The installation wizard gave me an error because account zmbackup@... already existed, so it did not complete installation procedure; so I deleted zmbackup@... account and run again the 1.2.3 installer, then it completed the installation without errors.
Is that the correct procedure? Is it mandatory to delete the zmbackup@... account before upgrading zmbackup software?

**Comment by lucascbeyeler** [comment]
Fixed - Version 1.2.5 does not require anymore the zmbackup account to be created to consider as a success.
