### ISSUE TITLE
invalid date ‘+%s’

### ISSUE THREAD

**Issue by antonzhelyazkov** [lucascbeyeler/zmbackup#131]
##### ISSUE TYPE:
- Bug Report

##### ENVIRONMENT VERSION
- Zmbackup Version: 1.2.3
- Zimbra Version: 8.8.9
- Linux Distribution & Version: Centos 7

##### SUMMARY

Hi Team,

I run manually ```sudo -u zimbra /usr/local/bin/zmbackup -f``` and I have got this error in my console ```invalid date ‘+%s’``` 

It seems that script could not get result from command ```date ‘+%s’```.

Server clock is in sync. We use chrony to keep our servers in sync. When I run manually I have got the following output:

```
[root@mx bash]# date ‘+%s’
date: invalid date ‘‘+%s\’’
[root@mx bash]# date +%s
1552292282
```
probably backticks in command are the problem ...

**Comment by cthart** [comment]
I have the same issue.
Zimbra 8.8.7_GA_1964
Ubuntu 16.04.6 LTS

**Comment by antonzhelyazkov** [comment]
@cthart Hi, I solved my issue with reinstall zmbackup.

**Comment by lucascbeyeler** [comment]
Closing the issue - new releases of Zmbackup does not appear the bug reported.
