### ISSUE TITLE
getting invalid user on installing for zcs 8.8.11

### ISSUE THREAD

**Issue by bumkailashkumar** [lucascbeyeler/zmbackup#132]
getting invalid user on installing for Zcs 8.8.11

Errors:
chown: invalid user: ‘y’5%)
sudo: unknown user: y (90%)
sudo: unable to initialize policy plugin
ERROR - Can't create the user. Executing rollback process
Error description: sudo: unknown user: y
sudo: unable to initialize policy plugin
Removing... Please wait while we made some changes.
installScript/deploy.sh: line 152: /etc/zmbackup/zmbackup.conf: No such file or directory

**Comment by ananiasfilho** [comment]
Please, @bumkailashkumar provide us more details as:
Linux version and release: Ubuntu (16.04, 14.04)/Centos(5,6,7)/RedHat(5,6,7)
Zimbra command result: **su - zimbra** then **zmcontrol -v** 
Zmbackup version:

**Comment by lucascbeyeler** [comment]
Closing the ticket - didn't receive an update from the creator
