### ISSUE TITLE
restore/import backup to another server

### ISSUE THREAD

**Issue by asep008** [lucascbeyeler/zmbackup#134]
##### ISSUE TYPE

- Question

##### ENVIRONMENT VERSION
- Zmbackup Version: 1.2.3
- Zimbra Version:  Release 8.8.6_GA_1906.RHEL7_64_20171130041047 RHEL7_64 FOSS edition.
- Linux Distribution & Version: Release 8.8.6_GA_1906.RHEL7_64_20171130041047 RHEL7_64 FOSS edition.

##### SUMMARY
i want to restore my backup to another server with different hostname server.

##### STEPS TO REPRODUCE

on the source server i am using this command to backup
```
zmbackup -f -d my.domain.com
```
and then i mount my backup directory to server restore and use this command to restore.
```
zmbackup -r full-20190906155310
```

##### ACTUAL RESULTS
```
Restore LDAP process with session full-20190906155310 started at Fri Sep  6 16:27:36 WIB 2019
Error during the restore process for account user@my.domain.com. Error message below:
user@my.domain.com: ldap_add: No such object (32)
        matched DN: dc=x,dc=y,dc=x
/usr/lib/python2.7/site-packages/urllib3/connectionpool.py:769: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)

http: warning: HTTP 404 no such item
<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
<title>Error 404 no such item</title>
</head>
<body><h2>HTTP ERROR 404</h2>
<p>Problem accessing /service/home/user@my.domain.com/. Reason:
<pre>    no such item</pre></p>
</body>

```
and then i try to create an object for that user@my.domain.com the result for restore like this
```
Error during the restore process for account user@my.domain.com. Error message below:user@my.domain.com: /usr/lib/python2.7/site-packages/urllib3/connectionpool.py:769: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
```
and if i open zimbra admin the use accounhave asterisk symbol **"*"** with description "this mail account uses external transport"

**Comment by lucascbeyeler** [comment]
Fixed in 1.2.5
