### ISSUE TITLE
Restoring Mailbox Issue

### ISSUE THREAD

**Issue by kmharish73** [lucascbeyeler/zmbackup#135]
While trying to restore from fullbackup the user mail are not getting restored, It is showing below error
zmbackup -r full-20190920112720
Restore LDAP process with session full-20190920112720 started at Fri Sep 20 12:21:05 IST 2019
Restore LDAP process with session full-20190920112720 completed at Fri Sep 20 12:21:05 IST 2019
Restore mail process with session full-20190920112720 started at Fri Sep 20 12:21:05 IST 2019Error during the restore process for account xxx@yyy.com. Error message below:xxx@yyy.com: usage: http [-h] [--version] [--json | --form] [--traceback]
            [--pretty | --ugly] [--headers | --body] [--style STYLE]
            [--auth AUTH] [--verify VERIFY] [--proxy PROXY]
            [--allow-redirects] [--file PATH] [--timeout TIMEOUT]
            METHOD URL [items [items ...]]
http: error: unrecognized arguments: --check-statusError 

ZMBackup version 1.2.3
Zimbra 8.8

**Comment by lucascbeyeler** [comment]
Fixed - dropped httpie in favor of cURL for future releases. Please try to use zmbackup 1.2.5
