### ISSUE TITLE
fullbackup doesn't work after deleting old backup 

### ISSUE THREAD

**Issue by Nill007** [lucascbeyeler/zmbackup#136]
i have deleted old backup from the location /opt/zimbra/backup/full* . Now im trying to take full backup using command  $ zmbackup -f, it shows nothing to do.
after adding some accounts in it, after fullbackup it backup only new change not all backup.
Also lists the old backup which is deleted awhile

**Comment by lucascbeyeler** [comment]
Did you delete the backup manually? If yes - that's the reason. Please avoid deleting backup manually and use zmbackup -d for that instead.
