### ISSUE TITLE
Email Alert not working on error only

### ISSUE THREAD

**Issue by killmasta93** [lucascbeyeler/zmbackup#144]
##### ISSUE TYPE
- Bug Report

##### ENVIRONMENT VERSION
- Zmbackup Version: 1.2.3
- Zimbra Version:8.8.15
- Linux Distribution & Version: ubuntu server 18.04

##### SUMMARY
the error email reports not working edited the /etc/zmbackup/zmbackup.conf 
to only error and tested by unmounting the backup directory 
which i got this error on the logs 

`Apr 10 22:09:01 mail zimbra[17959]: Zmbackup: The directory /mnt/bakzimbra does not found.`

i got the cron email saying this 

```
The directory /mnt/bakzimbra doesn't exist.
Some errors are found inside the config file. Please fix then and try again later.
```

but nothing goes to the admin email

Thank you

**Comment by lucascbeyeler** [comment]
Fixed - mail alert is working again after the changes made on 1.2.5
