### ISSUE TITLE
Restore issue

### ISSUE THREAD

**Issue by killmasta93** [lucascbeyeler/zmbackup#145]
Hi,
Currently trying to restore a mailbox and im getting this error 

zmbackup -r -ro full-20200515013010  comercial@mydomain.com test@mydomain.com
Restore mail process with session full-20200515013010 started at Sat May 16 00:13:16 -05 2020Error during the restore process for account comercial@mydomain.com. Error message below:http:
Restore mail process with session full-20200515013010 completed at Sat May 16 00:13:54 -05 2020

currently running zimbra 8.8.15 with zmbackup 1.2.3

Thank you

**Comment by gitjmrubio** [comment]
I tried a similar operation simulating a disaster recover situation.
Installed a second server, installed the zimbra software, then the zmbackup tooling.  Copied all the alias*, distlist*, inc* and full* directories to new server, set correct permisions as zimbra user, copied also the sessions.txt file and when I perform zmbackup -l it shows the information well.
After tried the zmbackup -r full-XXXX it shows some errors like below:
[zimbra@mail2 ~]$ zmbackup -r -m full-20200607013002
Restore mail process with session full-20200607013002 started at Sun Jun 14 00:44:31 CST 2020Error during the restore process for account account1@domain.example. Error message below:account1@domain.example:
http: warning: HTTP 400 cannot find remote serverError during the restore process for account account2@domain.example. Error message below:account2@domain.example:
http: warning: HTTP 400 cannot find remote serverError during the restore process for account account3@domain.example. Error message below:account3@domain.example:
http: warning: HTTP 400 cannot find remote serverError during the restore process for account account4@domain.example. Error message below:account4@domain.example:
http: warning: HTTP 400 cannot find remote serverError during the restore process for account account5@domain.example. Error message below:account5@domain.example:
http: warning: HTTP 400 cannot find remote serverError during the restore process for account account6@domain.example. Error message below:account6@domain.example:
http: warning: HTTP 400 cannot find remote serverError during the restore process for account account7@domain.example. Error message below:account7@domain.example:
http: warning: HTTP 400 cannot find remote serverError during the restore process for account account8@domain.example. Error message below:account8@domain.example:
http: warning: HTTP 400 cannot find remote server
Restore mail process with session full-20200607013002 completed at Sun Jun 14 00:44:39 CST 2020

On the admin panel, I see the accounts imported but no messages there.

Anyone can figure this out and help?  Thank you

**Comment by lucascbeyeler** [comment]
Fixed - new released of Zmbackup can now let you set the correct Zimbra Admin port, which can solve the issue above. Please try again with that version and if the problem happens again feel free to reopen this ticket.
