### ISSUE TITLE
issue with backing up

### ISSUE THREAD

**Issue by killmasta93** [lucascbeyeler/zmbackup#146]
Hi Currently having issue with the backup this is what im getting so far

```
Backup session full-20200517160206 started on Sun May 17 16:02:09 -05 2020
environment: line 21: /usr/bin/logger: Argument list too long
environment: line 21: /usr/bin/logger: Argument list too long
```
currently running zimbra 8.8.15 with zmbackup 1.2.3
Thank you

**Comment by lucascbeyeler** [comment]
"Fixed" - the logger should now point you to the correct reason for why you can't backup. Please try to use the most recent version of Zmbackup and try to solve the problem informed inside the log. If it's a code issue feel free to reopen this ticket
