### ISSUE TITLE
httpie version 

### ISSUE THREAD

**Issue by jorgemop** [lucascbeyeler/zmbackup#148]
On CentOS 6 the version of  httpie show this message on certains operation like zmbackup -r -m 

[root@ntplanta1 ~]# http --download https://www.2daygeek.com/wp-content/uploads/2019/04/Anbox-Easy-Way-To-Run-Android-Apps-On-Linux.png
usage: http [-h] [--version] [--json | --form] [--traceback]
            [--pretty | --ugly] [--headers | --body] [--style STYLE]
            [--auth AUTH] [--verify VERIFY] [--proxy PROXY]
            [--allow-redirects] [--file PATH] [--timeout TIMEOUT]
            METHOD URL [items [items ...]]

zmbackup version: 1.2.3 
CenOS 6.10 
Zimbra 7.8.11 p14 
httpie-0.1.6-1.of.el6.noarch.rpm

**Comment by lucascbeyeler** [comment]
Fixed - dropped httpie in favor of cURL. Please use the most recent version instead
