### ISSUE TITLE
Backups lager than 2GB cannot be restored.

### ISSUE THREAD

**Issue by Wodel** [lucascbeyeler/zmbackup#151]
##### ISSUE TYPE
- Bug Report

##### ENVIRONMENT VERSION
- Zmbackup Version: 1.2.3
- Zimbra Version: 8.8.15 patch 14
- Linux Distribution & Version: CentOS 7

##### SUMMARY
Backups lager than 2GB cannot be restored.
I am getting this error message : Error message below:/usr/lib/python2.7/site-packages/urllib3/connectionpool.py:769:

##### STEPS TO REPRODUCE
```
Restore a backup of 2.7GB
zmbackup -r -ro full-20200301010607 user@example.com   user-restore@example.com
Error : Error message below:/usr/lib/python2.7/site-packages/urllib3/connectionpool.py:769

Restore a backup of 1.9GB
zmbackup -r -ro full-20200401010607 user@example.com   user-restore@example.com
it works
```

##### ACTUAL RESULTS
```
I tried with other backups 3GB and 800MB and the same results : 
- Larger than 2GB : Error
- Lesser than 2GB : Works

I used strace, and I found that there is an overflowerror : read(3, "\nhttp: error: overflowerror: str"
Reading about httpie, it seems it does not support uploading files larger than 2GB.
The latest version of htpie 2.2.0 does not have support for lager files, this feature is meant to be available on httpie 2.3 which is in dev for now.
Since zmbackup is a bunch of bash scripts, could we use another tool other than httpie to upload larger files?
```

**Comment by bezunartea** [comment]
I also stumbled upon this issue, I have a few accounts whose backup files are well over 2GB, and cannot be restored... which actually defeats the main purpose for a backup. A backup file is totally useless when it cannot be restored.

I'm surprised that the actual recovery command is run as an http request to the web server. I guess there is no command line in zimbra for this purpose right?

**Comment by lucascbeyeler** [comment]
Hi, actually there is - on the enterprise. Which defeats the purpose of the zmbackup if you can pay for the enterprise...

**Comment by lucascbeyeler** [comment]
Fixed - stopped using httpie and instead I'm using back cURL. Closing ticket - a new release with cURL enabled will be available at the end of the day.
