### ISSUE TITLE
Question: how do I backup only one mailbox account?

### ISSUE THREAD

**Issue by HcKTR** [lucascbeyeler/zmbackup#154]
Hello, I start a backup in my ldap server as "zmbackup -f -m 1test@zimbratest.com" but it starts a full backup. How can I get 1test@zimbratest.com mailbox backup only? If I'm wrong, can you correct it please?

zmcontrol -v
Release 8.8.8_GA_2009.RHEL7_64_20180322150747 RHEL7_64 FOSS edition.

zmbackup -v
zmbackup version: 1.2.5

**Comment by lucascbeyeler** [comment]
The option is -r not -f

**Comment by karvox** [comment]
zmbackup can't get mailbox messages backup, just only ldif entries!? Why?

**Comment by lucascbeyeler** [comment]
Please open a different ticket but the problem is not Zmbackup. It's Zimbra - the API for a long time is bugged.
