### ISSUE TITLE
Error with -d or -a options

### ISSUE THREAD

**Issue by fug-azi** [lucascbeyeler/zmbackup#157]
##### ISSUE TYPE
- Bug Report

##### ENVIRONMENT VERSION
- Zmbackup Version: 1.2.5
- Zimbra Version: 8.8.15
- Linux Distribution & Version: CentOS 7

##### SUMMARY

Hello,
I'm trying to run full backup with ZMBACKUP with the option -d (one domain backup) or -a (one account backup).
With the -d option backup fail with message:
"ERROR - Can't extract accounts from LDAP - See log for more information"
in the log found this:
Jan 26 19:41:50 zimbra2 user[865]: Zmbackup: LDAP - Can't extract accounts from LDAP - Error below:
Jan 26 19:41:50 zimbra2 user[866]: Zmbackup: No such object (32)#012Matched DN: dc=it

With the -a option backup fail with message:
"/usr/local/lib/zmbackup/bash/BackupAction.sh: line 95: hd@sytis.it//,/\n/g: No such file or directory
Nothing to do. Closing..."

The full backup without options work correctly. I have test ZMBACKUP on two server and the error is the same.

##### STEPS TO REPRODUCE

zmbackup -f -d example.it
zmbackup -f -a test@example.it

Am I doing something wrong?

**Comment by lucascbeyeler** [comment]
According to EgemenErol:

A restore attempt broke my installation as well. It seems to be the ldiff replay that's breaking the ldap database. Ldap is then no longer accessible and after a restart zimbra can't get all services up and running.

zmbackup -r full-20210128163246 -ldp -a windows@domain.de --> This is breaking ldap

./libexec/zmslapadd /mnt/mail_backup2/zimbrabackup/full-20210128163246/windows@domain.de.ldiff --> WORKING!

This means the ldiff files created by zmbackup are definitly ok. Other variations of restore are breaking the installation as well, but I strongly assume it's the ldp part. Though I haven't tried a mailbox only restore yet.

Zimbra 8.8.15 GA Release on Centos 7

========

Posting here to avoid confusion between issues.

**Comment by lucascbeyeler** [comment]
I made a couple of changes for the LDAP restore and I believe should be working. Still testing just to make sure it will not break again.

**Comment by lucascbeyeler** [comment]
Closing the ticket - the version 1.2.6 should be working again.
