### ISSUE TITLE
Question:  Can we restore the Deleted User mailbox using zmbackup.

### ISSUE THREAD

**Issue by samrocks1011** [lucascbeyeler/zmbackup#163]
@lucascbeyeler 

I would like to know if we can restore the deleted user from the Backup.

Regards,
Sandeep Patel

**Comment by killmasta93** [comment]
go to the restore file you want 

`zmbackup -r -m inc-20200410003052 youemail@domain.com`

**Comment by samrocks1011** [comment]
@killmasta93  

So the script will create the user again and restore it. Or we need to create the user first and that run the restore command.

**Comment by killmasta93** [comment]
create the user first 

then run the command that i gave you

**Comment by samrocks1011** [comment]
@killmasta93  Thank You.

I do the same.
