### ISSUE TITLE
Cronjob question?

### ISSUE THREAD

**Issue by killmasta93** [lucascbeyeler/zmbackup#164]
Hi,
I was wondering if its possible to backup full every 3 months i tried this

`0 0 1 */3 *     zimbra    zmbackup -f`

but not sure how i can test it?

Thank you

**Comment by ananiasfilho** [comment]
You are right!
Look it:
30 0 1 */3 * zimbra zmbackup -f
At **_00:30_** on **_day-of-month 1_** in **_every 3rd month_** (month 3,6,9 and 12).
