### ISSUE TITLE
Emails are not recovered correctly from full bakcup

### ISSUE THREAD

**Issue by soniqsoft** [lucascbeyeler/zmbackup#167]
##### ISSUE TYPE
- Bug Report

##### ENVIRONMENT VERSION
- Zmbackup Version: 1.26
- Zimbra Version: 8.8.15_GA_3869
- Linux Distribution & Version: Ubuntu 18.04 LTS

##### SUMMARY
Started to recover email account with m option (mailbox only) and received recovered partially with error:
ERROR: zclient.IO_ERROR (Read timed out) (cause: java.net.SocketTimeoutExce|
ption Read timed out)

##### STEPS TO REPRODUCE
```
Recover mailbox account from full backup session
zmbackup -r -m <session> <email>
<!--
ACTUAL RESULTS: What happened when you did the steps before.
-->
##### ACTUAL RESULTS
```
 ERROR: zclient.IO_ERROR (Read timed out) (cause: java.net.SocketTimeoutExce|
ption Read timed out)
```

**Comment by ananiasfilho** [comment]
Its said "Time Out"
Try restore backup using zmmailbox

zmmailbox -z -m user@example.com **_-t 0_** postRestURL "//?fmt=tgz&resolve=reset" /backup/user@example.com.tar.gz

-t 0 is the tip that say to zmmailbox to run command without timeout limit.

**Comment by soniqsoft** [comment]
Thank you @ananiasfilho!
I found it earlier but forgot to mention it here.
Thanks a lot anyway.

**Comment by andreagobetti** [comment]
For me the `-t 0` option was not enough, but I managed to solve this issue increasing the `socket_so_timeout` value from 30000 to `3000000`

using these commands:

```
zmlocalconfig -e socket_so_timeout=3000000
zmlocalconfig --reload
```

Like _mgarbo_ suggested here: https://community.zextras.com/forum/zimbra-ose-9-by-zextras/zmmailbox-postresturl-doesnt-work/
