### ISSUE TITLE
zmbackup error

### ISSUE THREAD

**Issue by thiagowarwick** [lucascbeyeler/zmbackup#171]
hello, I'm having the following problem when trying to backup an open mailbox:
zimbra@mail:/usr/local/lib/zmbackup/bash$ zmbackup -f -a thiago.marinho@dominio.com
/usr/local/lib/zmbackup/bash/BackupAction.sh: line 100: thiago.marinho@dominio.com//,/\n/g: No such file or directory
Nothing to do. Closing...

##### ISSUE TYPE
- Bug Report
- Feature Idea
- Question
- Enhancement

##### ENVIRONMENT VERSION
- Zmbackup Version:
- Zimbra Version:
- Linux Distribution & Version:

##### STEPS TO REPRODUCE
```
```

##### ACTUAL RESULTS
```
```

**Comment by ananiasfilho** [comment]
Have you been solved your issue? If not, can you please describe your environment so we can help better.

**Comment by thiagowarwick** [comment]
> Você foi resolvido o seu problema? Se não, você pode descrever seu ambiente para que possamos ajudar melhor.

Good morning! Solved, thank you.
