### ISSUE TITLE
Process to restore the zimbra backup

### ISSUE THREAD

**Issue by samrocks1011** [lucascbeyeler/zmbackup#18]
Dear Sir,

I have successfull taken eh full backup of zimbra using zmbackup -f command.
The new zimbra machine is ready and trying to restore the backup using zmbackup -r. But the error comes **"Error!  Incorrect options"**  Please let me know the option that i need to include to restore the  full backup.

**Comment by lucascbeyeler** [comment]
Dear @samrocks1011 

To do a restore you need to inform what kind of restore do you want. If it is a mailbox restore, use -m, or if you trying to restore a ldap account use -ldp. For example:

`zmbackup -r -ldp <session> <account>`

`zmbackup -r -m <session> <account>`

zmbackup does not restore yet the ldap and the mailbox at the same time.

Regards,
Lucas Costa Beyeler

**Comment by lucascbeyeler** [comment]
Dear @samrocks1011 

As you didn't return if this answer your question, I'm closing this issue. Feel free to re-open if needed.

Regards,
Lucas Costa Beyeler

**Comment by samrocks1011** [comment]
Dear @lucascbeyeler 
Sorry for the late reply. I executed the following command **"zmbackup -r -ldp full-20170318123250 sandeep@sjcet.co.in"** . I received a output saying **"No backup found. Impossible to restore"**. 
Backup Directory in zmconfig.conf file:- /backup
Owner of the /backup is zimbra.
full backup session in sessions.txt file  :- full-20170318123250

Is something I am doing wrong. Please help me.

**Comment by lucascbeyeler** [comment]
Dear @samrocks1011 

Which version are you using?

To get the version, please run "zmbackup -v" and post here. It's actually just this. If the sessions.txt aren't excluded, the restore should be working.

Regards,
Lucas Costa Beyeler

**Comment by lucascbeyeler** [comment]
Dear @samrocks1011

I made a new update in zmbackup because I could simulate your error even in the most recent release. Please, update your version and try again to see if the bug persist.

Thanks for your support.

**Comment by samrocks1011** [comment]
zmbackup version: 1.0.1

**Comment by lucascbeyeler** [comment]
@samrocks1011 

First: Did you try the new release? I launched yesterday the version 1.0.2.

Second: Can you tell me if the backup for this account was done correctly? Can you tell me if the file is not empty?

Regards,
Lucas Costa Beyeler

**Comment by samrocks1011** [comment]
@lucascbeyeler 

I haven't tried with the new version 1.0.2.  I will be testing the new version today and will provide the status.

**Comment by samrocks1011** [comment]
@lucascbeyeler 
It was successful restore. I was trying to restore the data to fresh zimbra on new server. The new server was not having domain. When i created one domain and run the restore process I was able to successful restore the User and mailbox. 
Thanks for the support.

**Comment by lucascbeyeler** [comment]
@samrocks1011 

Thanks for the return. If the problem return, please feel free to reopen the issue

**Comment by jorgemop** [comment]
Full backup going well 
Incremental backup apparently going well  

I delete an account for test, later try to recover it with -r -m and full session 

and i gave this: 

[zimbra@asd ~]$ zmbackup -r -m full-20200617121733 scompras@domain.com.ve
Restore mail process with session full-20200617121733 started at Thu Jun 18 15:18:28 -04 2020Error during the restore process for account scompras@domain.com.ve. Error message below:scompras@domain.com.ve: usage: http [-h] [--version] [--json | --form] [--traceback]
            [--pretty | --ugly] [--headers | --body] [--style STYLE]
            [--auth AUTH] [--verify VERIFY] [--proxy PROXY]
            [--allow-redirects] [--file PATH] [--timeout TIMEOUT]
            METHOD URL [items [items ...]]
http: error: unrecognized arguments: --check-status
Restore mail process with session full-20200617121733 completed at Thu Jun 18 15:18:28 -04 2020

The file exist 
[zimbra@server1$ ls -lha scompras@domain.com.ve.tgz
-rw-r----- 1 zimbra zimbra 6.0G Jun 17 17:02 scompras@domain.com.ve.tgz 

what i'm doing wrong ? thanx in advance
