### ISSUE TITLE
Zimbra incremental backup doens't work.

### ISSUE THREAD

**Issue by mkaliyannan** [lucascbeyeler/zmbackup#19]
I am not sure Incremental backups not working 

```
 zmbackup -i
Running the Incremental Backup - Please wait...
WARN: stash@xxxxxx.ca already has backup today. Nothing to do.
Nothing to do..

```

Tried with account name as well : It's not working.

** Thanks for your great effort **

**Comment by lucascbeyeler** [comment]
Hello @mkaliyannan,

Can you tell me if you already did a backup today? If you did the zmbackup does not do more than 1 backup per day for each option (full and incremental count as the same). I'm going to create a --force option to override this, and complete de documentation to inform this limitation.

Thanks for your support.

Regards,
Lucas Costa Beyeler

**Comment by lucascbeyeler** [comment]
Dear @mkaliyannan,

As you didn't return if this answer your question, I'm closing this issue. Feel free to re-open if needed.

Regards,
Lucas Costa Beyeler

**Comment by mkaliyannan** [comment]
Hey @lucascbeyeler  sorry for the delay. Thanks .. I did backup already.. I will let you kow if any issues.
