### ISSUE TITLE
Incremantal backup issue

### ISSUE THREAD

**Issue by samrocks1011** [lucascbeyeler/zmbackup#24]
@lucascbeyeler 

Incremental backup take backup of any new user is created in zimbra. It does not take the backup of modified data of current user present at the time of Full backup.  
Command executed zmbackup -i 
Please help me with the solution.

**Comment by lucascbeyeler** [comment]
Hello @samrocks1011,

Can you describe better what's happening with the process? This explanation you gave me were a little confuse, to be honest.

Regards,
Lucas Costa Beyeler

**Comment by lucascbeyeler** [comment]
Dear @samrocks1011,

As you didn't answer my question, I'm closing this issue. Feel free to re-open if needed.

Regards,
Lucas Costa Beyeler
