### ISSUE TITLE
Error RestoreonAccount 

### ISSUE THREAD

**Issue by MarcielMeurer** [lucascbeyeler/zmbackup#31]
The script for restore not found the archive in  /backup/sessions.txt
My backup directory is in /opt/zimbra/backup
The  message say SUCCESS, but isn't really.

_ $ zmbackup -r -ro  full-20170417111450  user1@mydomain.com restore@mydomain.com
grep: /backup/sessions.txt: Arquivo ou diretório não encontrado
Restore mail process started at - Seg Abr 17 11:29:21 -03 2017

Restoring Session - restore@mydomain.com
Session restore@mydomain.com restored with SUCCESS

Restore mail process completed at - Seg Abr 17 11:29:21 -03 2017 _

**Comment by lucascbeyeler** [comment]
Good afternoon @MarcielMeurer ,

Could you please update the zmbackup to the release 1.1.1 and try again? I think i might fixed your bug.

Regards,
Lucas Costa Beyeler

**Comment by MarcielMeurer** [comment]
@lucascbeyeler , i had updated,  before adjust the line 136 , with the adjust the message don't have displayed. The restore mensagem is SUCCESS, but the restore don't execute. 
I'm attached the script;
[debug_restore.txt](https://github.com/lucascbeyeler/zmbackup/files/926379/debug_restore.txt)

I used  zmbackup version: 1.1.1



Regards,
Marciel Meurer

**Comment by lucascbeyeler** [comment]
@MarcielMeurer , I fixed this time the zmbackup for good! It wasn't the fact your folders was inside /opt/zimbra/backup that you can't do any restore. The Restore on Account option stopped working after the last update and I didn't notice. I fixed now and release a new update. Could you please update your version and try again?

Regards,
Lucas Costa Beyeler

**Comment by MarcielMeurer** [comment]
@lucascbeyeler Thanks, its Working. I have successfully tested with unique full backup. Question: I can restore from incremental backup?

**Comment by lucascbeyeler** [comment]
@MarcielMeurer, yes you can.

**Comment by lucascbeyeler** [comment]
Dear @MarcielMeurer,

I'm closing this issue, as it's already fixed. Feel free to reopen if the bug occur again.

Regards,
Lucas Costa Beyeler
