### ISSUE TITLE
ldap_bkp not implemented

### ISSUE THREAD

**Issue by saschadd** [lucascbeyeler/zmbackup#34]
Hi lucas,
when i try to backup ldap i get an error message that ldap_bkp in line 516 is not implemented.
It looks like that the function is missing in the script.

**Comment by lucascbeyeler** [comment]
Good morning @saschadd ,

Could you please try again? I fixed this bug in release 1.1.3.

Regards,
Lucas Costa Beyeler

**Comment by saschadd** [comment]
Hi Lucas,
ldap backup works! Thank you.
Don't have the time to test ldap restore at the moment.

Regards, Sascha

**Comment by lucascbeyeler** [comment]
@saschadd Thanks for your answer and your support. I'm closing the issue, but feel free to reopen if the bug returns.

Regards,
Lucas Costa Beyeler
