### ISSUE TITLE
max parallel processes

### ISSUE THREAD

**Issue by antonzhelyazkov** [lucascbeyeler/zmbackup#37]
Hi,

it seems that MAX_PARALLEL_PROCESS works wrong. If I set this property to 2 it starts 4 parallel processes.

**Comment by lucascbeyeler** [comment]
Good morning @antonzhelyazkov ,

Sorry for the later answer, but this bug is already fixed in the release 1.1.4. Can you please try again?

Regards,
Lucas Costa Beyeler

**Comment by antonzhelyazkov** [comment]
Hi @lucascbeyeler,

It works correct at the moment.
