### ISSUE TITLE
edit cron job

### ISSUE THREAD

**Issue by antonzhelyazkov** [lucascbeyeler/zmbackup#38]
Hi,

It seems that house keep - zmbhousekeep could not be started from cron, bebause in /etc/cron.d/zmbackup.cron house keep script is named as zmhousekeep. Could you replace zmhousekeep with zmbhousekeep

**Comment by lucascbeyeler** [comment]
Good morning @antonzhelyazkov ,

Sorry for the later answer, but this bug is already fixed in the release 1.1.4. Can you please try again?

Regards,
Lucas Costa Beyeler

**Comment by antonzhelyazkov** [comment]
Hi @lucascbeyeler,

Cron is fixed.
