### ISSUE TITLE
I can't run backups | DNS SRV: out of memory?

### ISSUE THREAD

**Issue by zenatuz** [lucascbeyeler/zmbackup#41]
Hey Lucas, 

I'm trying do a backup, but when I run the command, I have this issue, `DNS SRV: out of memory?`.

```
[zimbra@webmail ~]$ zmbackup -f user@domain
Running the Full Backup - Please wait...
DNS SRV: out of memory?
Backup finished!
[zimbra@webmail ~]$ zmbackup -v
zmbackup version: 1.1.4
```
How can I fix it? Do I need to do any different configuration when I run the wizard?

P.S.: I did the installation process without change any option.

Thanks.

**Comment by lucascbeyeler** [comment]
Good evening @zenatuz ,

The problem probably is the multithread feature. For default, the zmbackup work with 3 threads at the same time, but it's looks like your server don't work very well with this amount. Can you please open the file /etc/zmbackup/zmbackup.conf and change the MAX_PARALLEL_PROCESS option from 3 to 1 and try again?

Regards,
Lucas Costa Beyeler

**Comment by zenatuz** [comment]
Hey @lucascbeyeler,

I've found the solution, I needed to change the value of a few variables in the zmbackup.conf, puting the server IP address.
I've found the solution in this post: https://github.com/bggo/Zmbkpose/issues/43

Thanks anyway.

**Comment by lucascbeyeler** [comment]
Good morning @zenatuz ,

Strange that you need to change this value in your conf, because the zmbackup_wizard should provide the correct value. Does the field was empty?

Question: do you put the IP address of your server inside the /etc/hosts?

I'm marking this as bug related to zmbackup_wizard for now.

Regards,
Lucas Costa Beyeler

**Comment by zenatuz** [comment]
Hey @lucascbeyeler, good afternoon.

No, the fields wasn't empty, but they had a variable, I don't remember wich were. 
I'm not sure about the /etc/hosts/, maybe this was the source of the problem. I'll check later and let you know about this setting.

Thanks for the feedback.

Renato Batista.

**Comment by zenatuz** [comment]
Hey @lucascbeyeler, 

Settings were ok on /etc/hosts.
I don't know what happened during the installation. Hehe.

Regards.

**Comment by lucascbeyeler** [comment]
Closing this issue because this bug was fixed in branch DEV
