### ISSUE TITLE
incremental backup issue

### ISSUE THREAD

**Issue by lowlowtony** [lucascbeyeler/zmbackup#45]
Hello, first of all thanks for the script.
My zimbra version - Release 8.7.11_GA_1854.RHEL7_64_20170531151956 RHEL7_64 FOSS edition. 

I ran into strange thing - with total mailbox size 32gb increment backup lasts more than 3 days. 

SESSION: inc-20170811020001 started on Fri Aug 11 02:00:03 EEST 2017
SESSION: inc-20170811020001 completed in Mon Aug 14 15:42:11 EEST 2017

At the same time full backup lasts half an hour. 
Is it normal?

**Comment by lucascbeyeler** [comment]
Hi @lowlowtony,

No, this not normal. If you try again the same process, the bug occurs? Can you check the size of the incremental and see if it is lower than the full backup? This is installed in the same server your Zimbra is? 

Can you check the resource of your machine at that moment? Maybe some process consumed all the CPU during the weekend, maybe even the Zmbackup is the culprit. Try modifing the MAX_PARALLEL_PROCESS inside /etc/zmbackup/zmbackup.conf to something lower and try again.

Another thing, can you tell me the version of your Zmbackup? Just run "zmbackup -v"

Thanks for your support and have a nice week!

Regards,
Lucas Costa Beyeler

**Comment by lowlowtony** [comment]
1. I've tried it several times and nothing changes. In crontab i exclude increment backups but there are some processes still alive after 3 days and temp folders named FJ1n Pnms PvNZ exist in backup folder.
2. Size of successful inc backup is 78mb and looks correct. 
3. Yes, the same Zimbra server.
4. Zabbix average stats for weekend - CPU consumption 30% after starting inc backups, memory 3.7gb/6gb with swap 1gb.
5. zmbackup version: 1.1.6
6. MAX_PARALLEL_PROCESS = 3 , okay now i reduce to 1 and will try again, after all inc backups will finish and give you feedback. 

Thanks.

**Comment by lowlowtony** [comment]
Okay. Nothing changes. Increment backup lasts few days.
Furthermore i installed new zimbra server for our new client. Mailbox size - 10gb, zmbackup version: 1.1.6, MAX_PARALLEL_PROCESS = 1, zimbra version - 8.7.11, increment backup still working after 9 hours.

**Comment by lucascbeyeler** [comment]
@lowlowtony , good night. Sorry for the long delay to answer you. I made some modifications inside Zmbackup to kill wget after 5 seconds if the connection doesn't work. 

Another thing I want to ask about the incremental: did you try use localhost (127.0.0.1) as MAILHOST inside zmbackup.conf? How many accounts are you trying backing up?

I'm trying to simulate your problem, but in none of my tests the zmbackup -i take long time to run. Can you show me the command you are using to do the incremental?

Regards,
Lucas Costa Beyeler

**Comment by lucascbeyeler** [comment]
Hello @lowlowtony ,

I'm closing this issue, but you can reopen if you need. Remember to answer my questions before reopen.

Regards,
Lucas Costa Beyeler
