### ISSUE TITLE
backup zimbra server configuration

### ISSUE THREAD

**Issue by antonzhelyazkov** [lucascbeyeler/zmbackup#53]
ISSUE TYPE: Question

ENVIRONMENT VERSION: Zimbra

SUMMARY: Zimbra backup server configuration

Hi,

I am looking for procedure how to backup zimbra server configuration. Do you have ideas how to backup server configuration?

**Comment by lucascbeyeler** [comment]
All of them? Sorry @antonzhelyazkov, I don't know an easy way to backup all of them. I have plans to implement this in the future. Maybe the backup of the entire base solve your problem?

Regards,
Lucas Costa Beyeler

**Comment by antonzhelyazkov** [comment]
Thank you lucascbeyeler
