### ISSUE TITLE
parallel: Error: Command (--no-notice) starts with '-'. Is this a wrong option?

### ISSUE THREAD

**Issue by andreaPress** [lucascbeyeler/zmbackup#54]
Hi,
I'm sorry but we're on ZCS-8.7.11 and I've some problems with this backup script.

zmbackup --full
parallel: Warning: YOU ARE USING --tollef. IF THINGS ARE ACTING WEIRD USE --gnu.
parallel: Warning: --tollef is obsolete and will be retired 20140222.
parallel: Warning: See: http://lists.gnu.org/archive/html/parallel/2013-02/msg00018.html
Backup session full-20171127111316 started on Mon Nov 27 11:13:16 CET 2017
parallel: Error: Command (--no-notice) starts with '-'. Is this a wrong option?
Backup session full-20171127111316 finished on Mon Nov 27 11:13:17 CET 2017
ls: cannot access /opt/zimbra/backup/full-20171127111316/*.ldiff: No such file or directory

What am I doing wrong?

My parallel version is:
parallel --version
WARNING: YOU ARE USING --tollef. IF THINGS ARE ACTING WEIRD USE --gnu.
GNU parallel 20130522

Thanks!!
Andrea

**Comment by lucascbeyeler** [comment]
Hello @andreaPress,

Can you please answer the issue form for me? I need the following questions answered to start checking your problem:

##### ENVIRONMENT VERSION
- Zmbackup Version:
- Zimbra Version:
- Linux Distribution & Version:

Regards,
Lucas Costa Beyeler

**Comment by andreaPress** [comment]
Hi,
thanks for the reply, here's the information you asked for:

Zmbackup Version: latest from github
Zimbra Version: 8.7.11 GA Release
Linux Distribution & Version: Centos 6

Thank you very much.
Kind Regards,
Andrea

**Comment by lucascbeyeler** [comment]
@andreaPress,

Sorry for the delay, can you test with the new release if the bug persist?

Regards,
Lucas Costa Beyeler

**Comment by ondrejneufinger** [comment]
Hello,
I have 
zimbra 8.7.11
centos 6.9
zmbackup version: 1.2.0 - Release Candidate 2
and it is working
Thank you

**Comment by andreaPress** [comment]
Hi,
don't worry for the delay.
Thank you very much.
Now it's working like a charm.

**Comment by lucascbeyeler** [comment]
Hello @andreaPress and @ondrejneufinger,

Good to know that it's working.

I'm closing this issue as solved.

Thanks for your support and have a nice day!

Regards,
Lucas Costa Beyeler
