### ISSUE TITLE
Support to Zimbra 8.8

### ISSUE THREAD

**Issue by lucascbeyeler** [lucascbeyeler/zmbackup#57]
##### ISSUE TYPE
- Feature Idea

##### ENVIRONMENT VERSION
- Zmbackup Version: 1.2 RC
- Zimbra Version: 8.8
- Linux Distribution & Version: Any Distribution

##### SUMMARY

We need to validate the script in the new release of Zimbra if it is working with no problem.

**Comment by sardigital** [comment]
Zimbra 8.8.6 backuped.
SESSION: full-20180120153225 completed in Sat Jan 20 21:16:55 +04 2018

**Comment by mailanetworks** [comment]
Hi @sardigital 

 [zimbra@mail ~]$ zmcontrol -v
Release 8.8.6_GA_1906.RHEL7_64_20171130041047 RHEL7_64 FOSS edition.
[zimbra@mail ~]$ zmbackup -v
zmbackup version: 1.2.0 - Release Candidate 2
[zimbra@mail ~]$ zmbackup -f
Nothing to do. Closing...

If I change the address on the zmbackup.conf from 127.0.0.1 to the real address, then nothing gets backuped, although you'll receive the above message.

Thanks,

**Comment by lucascbeyeler** [comment]
Hi @mailanetworks and @sardigital, I'm closing this issue because RC2 is working with Zimbra 8.8 in CentOS 6/7 and Ubuntu 14/16.

About the problem that it is not backing up: you need to point Zmbackup to the address your LDAP is listening. The first thing the script will do is get all the accounts that need to backed up from there.

If the problem persist, please open a issue exclusive for this problem with the description of the environment.

Regards,
Lucas Costa Beyeler
