### ISSUE TITLE
Backup and restore to a specific domain

### ISSUE THREAD

**Issue by alandma** [lucascbeyeler/zmbackup#65]
ISSUE TYPE
Feature Idea

ENVIRONMENT VERSION
Zmbackup Version: Any
Zimbra Version: Any
Linux Distribution & Version: Any

SUMMARY
New feature to backup and restore to a specific domain only.

**Comment by lucascbeyeler** [comment]
Hello @alandma,

I'm closing this issue because what you asked is already implemented in the branch 1.2-version. Fell free to reopen this issue if any problems occur.

Regards,
Lucas Costa Beyeler
