### ISSUE TITLE
zmbackup single mail account restore issue

### ISSUE THREAD

**Issue by somnathndy** [lucascbeyeler/zmbackup#66]
##### ISSUE TYPE
- Bug Report
- Feature Idea
- Documentation Report
- Question 
- Checklist

Question

##### ENVIRONMENT VERSION
- Zmbackup Version: 1.2.0, release candidate 2
- Zimbra Version: 8.8.6
- Linux Distribution & Version: CentOS 6.9

##### SUMMARY
I am doing a test with Zimbra OSE 8.8.6 installed on CentOS 6.9. It is configured properly and working fine. I have installed Zmbackup (version 1.2.0, release candidate 2) after downloading from Github for mail account backup. It is also doing it's backup work properly without any failure.

Problem is arising when I am trying to restore any account from the full backup. Whenever I am trying to restore any ldap information it is doing properly(perhaps as no error message is there) but when I am trying to restore the mail account( with "-m" option) it is giving error message as follows -
______________________________________________________________________
[zimbra@mail2 ~]$ zmbackup -r -ldp full-20180217170655 abhatta@sailrmd.co.in
Restore LDAP process with session full-20180217170655 started at Tue Feb 27 13:12:53 IST 2018
Restore LDAP process with session full-20180217170655 completed at Tue Feb 27 13:12:54 IST 2018
_______________________________________________________________________
[zimbra@mail2 ~]$ zmbackup -r -m full-20180217170655 abhatta@sailrmd.co.in
Restore mail process with session full-20180217170655 started at Tue Feb 27 13:14:15 IST 2018

Error during the restore process for account abhatta@sailrmd.co.in. Error message below:
abhatta@sailrmd.co.in: /bin/bash: http: command not found
Restore mail process with session full-20180217170655 completed at Tue Feb 27 13:14:15 IST 2018
_________________________________________________________________________

Please note, the server I am restoring to is a different server(mail2.sailrmd.co.in) from the source server(mail1.sailrmd.co.in).

##### STEPS TO REPRODUCE
```
```

##### ACTUAL RESULTS
```
```

**Comment by lucascbeyeler** [comment]
Hello @somnathndy,

This bug was fixed right now in the branch 1.2-version. Sorry for the long delay. Before the end of this week a new release will be launched with this fix.

Thanks for your support.

Lucas Costa Beyeler
