### ISSUE TITLE
New feature: backingup only active accounts

### ISSUE THREAD

**Issue by cribeironascimento** [lucascbeyeler/zmbackup#69]
ISSUE TYPE

- Feature Idea
ENVIRONMENT VERSION

- Zmbackup Version: 1.2.0 RC2

- Zimbra Version: any

- Linux Distribution & Version: any
SUMMARY
At the moment, the command zmbackup -f realize a full backup routine to all accounts. The new feature this a option to backup only active accounts.

**Comment by lucascbeyeler** [comment]
Hello @cribeironascimento,

A new option inside /etc/zmbackup/zmbackup.conf was included to enable or disable the backup for only active accounts. This new feature will be present in the next release.

I'm closing this issue because the task was already done.

Regards,
Lucas Costa Beyeler
