### ISSUE TITLE
Installation won't work if complex passwords are mandatory

### ISSUE THREAD

**Issue by mailanetworks** [lucascbeyeler/zmbackup#76]
ISSUE TYPE:  Bug Report
ENVIRONMENT VERSION: 
- Zmbackup Version: 1.2.1
- Zimbra Version: 8.8.8
- Linux Distribution & Version: Centos 7
##### SUMMARY
We use mandatory rules for accounts where users need to choose a strong password with capital letters, characters and numbers. 
The password generated by the script doesn't create a password strong enough and fails.

##### STEPS TO REPRODUCE
Try to install in a environment that forces passwords with these requirements.
##### ACTUAL RESULTS
Install fails

**Comment by lucascbeyeler** [comment]
Hello @mailanetworks,

I don't think creating a strong password will be the way to solve any problem. Sooner or later I will need to generate a patch for another even stronger password.

What I gonna do is still generate this weak password, but give you an option to input your password instead. Do you think this is a good way to solve your problem?

Regards,
Lucas Costa Beyeler

**Comment by mailanetworks** [comment]
Hi Lucas, 
It'll be perfect!
Thanks

**Comment by lucascbeyeler** [comment]
Hello @mailanetworks,

Could you try again? Please use the branch 1.2-version to install your Zmbackup. This fix will be included in version 1.2.2 after I finish developing all the new features and bugfix.

Regards,
Lucas Costa Beyeler

**Comment by mailanetworks** [comment]
Works like a charm!

Many thanks!!!
