### ISSUE TITLE
Zmbackup não roda na cron do ubuntu 16.04

### ISSUE THREAD

**Issue by ananiasfilho** [lucascbeyeler/zmbackup#78]
##### ISSUE TYPE
- Bug Report

##### ENVIRONMENT VERSION
- Zmbackup Version:
zmbackup version: 1.2.0 - Release Candidate 2

- Zimbra Version:
Release 8.8.6.GA.1906.UBUNTU16.64 UBUNTU16_64 FOSS edition.

- Linux Distribution & Version:
Ubuntu 16.04.4 LTS 
Linux 4.4.114-mainline-rev1 #1 SMP Thu Feb 1 16:16:01 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

##### STEPS TO REPRODUCE
```
```
cat /etc/zmbackup/zmbackup.conf |grep -v -E "^#|^$"
BACKUPUSER=zimbra
WORKDIR=/opt/zmbackup/backups
ADMINUSER=zmbackup@dominio.com.br
ADMINPASS=1234567890
LDAPSERVER=ldap://xxx.yyy.zzz.www:389
MAILHOST=xxx.yyy.zzz.www
LDAPADMIN=uid=zimbra,cn=admins,cn=zimbra
LDAPPASS=1234567890
LOGFILE=/opt/zimbra/log/zmbackup.log
EMAIL_NOTIFY=admin@dominio.com.br
MAX_PARALLEL_PROCESS=3
ROTATE_TIME=7
LOCK_BACKUP=false
SESSION_TYPE=TXT
 
################################################################################################
################################################################################################
################################################################################################
 
cat /etc/cron.d/zmbackup.cron
###############################################################################
#                             ZMBACKUP CRON FILE                              #
###############################################################################
# This file is used to manage the time and day each backup activity will be
# executed. Please modify this file rather than create a new one.
# Default values for each activity:
#       Full Backup:            Every Sunday at 1:30 AM
#       Incremental:            From Monday to Saturday at 1:30 AM
#       Alias:                  Every day at 0:30 AM
#       Distribution List:      Every day at 1 AM
#       Backup Rotation:        Every day at Midnight
###############################################################################
#                             ZMBACKUP VARIABLES                              #
###############################################################################
SHELL=/bin/bash
PATH=/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/bin
MAILTO=root
30 1  * * 0     zimbra    zmbackup -f
0  1  * * *     zimbra    zmbackup -f -dl
30 0  * * *     zimbra    zmbackup -f -al
30 1  * * 1-6   zimbra    zmbackup -i
0  0  * * *     zimbra    zmbackup -hp
 
###############################################################################
#                          ZMBACKUP - OTHER OPTIONS                           #
###############################################################################
# Mailbox Backup:     Every day at 1:30AM
# LDAP Backup:        Every day at 1:00AM
###############################################################################
# 30 1 * * *      zimbra    zmbackup -f -ldp
# 30 1  * * 0     zimbra    zmbackup -f -m
 
################################################################################################
################################################################################################
################################################################################################
Cron está rodando
 
ps aux|grep -i cron
root      3858  0.0  0.0  27732  3044 ?        Ss   Apr04   0:02 /usr/sbin/cron -f
 
Cron está iniciando como serviço no ubuntu
systemctl |grep cron
cron.service                                        loaded active running   Regular background program processing daemon
 
################################################################################################
################################################################################################
################################################################################################
##### ACTUAL RESULTS
```
```

**Comment by lucascbeyeler** [comment]
Hello @ananiasfilho,

I made the change you asked. Now the zmbackup will install a file called "zmbackup", not zmbackup.cron.

Regards,
Lucas Costa Beyeler
