### ISSUE TITLE
Define notification sender email

### ISSUE THREAD

**Issue by ananiasfilho** [lucascbeyeler/zmbackup#79]
##### ISSUE TYPE
- Feature Idea

##### ENVIRONMENT VERSION
- Zmbackup Version:
- Zimbra Version:
- Linux Distribution & Version:

##### SUMMARY
hability to define notification sender email address.
Example:
under zmbackup.conf define NOTIFICATION_SENDER=alert@domain.com
or under installation:
List all admins emails and select one OR define "Notification sender email address - user@domain.com".

##### STEPS TO REPRODUCE
```
```

##### ACTUAL RESULTS
```
```

**Comment by lucascbeyeler** [comment]
Hello @ananiasfilho 

I'm closing this issue because I implemented this issue in the branch 1.2.2

Regards,
Lucas Costa Beyeler
