### ISSUE TITLE
Zmbackup trying to check size of folders that does not exist during a failure

### ISSUE THREAD

**Issue by lucascbeyeler** [lucascbeyeler/zmbackup#83]
##### ISSUE TYPE
- Bug Report

##### ENVIRONMENT VERSION
- Zmbackup Version: 1.2.1
- Zimbra Version: any
- Linux Distribution & Version: any

##### SUMMARY
Zmbackup return error when try to send the e-mail, but the status is FAILURE.

##### STEPS TO REPRODUCE
```
zmbackup -f -m
```
##### ACTUAL RESULTS
```
ERROR - Can't extract accounts from LDAP - See log for more information
du: cannot access '/opt/zimbra/backup/mbox-20180418221655': No such file or directory
ls: cannot access /opt/zimbra/backup/mbox-20180418221655/*.tgz: No such file or directory
```

**Comment by lucascbeyeler** [comment]
FIXED

**Comment by jonasteixeira** [comment]
What procedure did you take to solve it?
