### ISSUE TITLE
Cannot install zmbackup

### ISSUE THREAD

**Issue by guinuxbr** [lucascbeyeler/zmbackup#87]
ISSUE TYPE - Bug Report

ENVIRONMENT VERSION
- Zmbackup Version: Latest from Github
- Zimbra Version: 8.8.5
- Linux Distribution & Version: Ubuntu Server 16.04 LTS

SUMMARY
To reproduce, I just have to try to install.

STEPS TO REPRODUCE
```
git clone -b 1.2-version https://github.com/lucascbeyeler/zmbackup.git
# cd zmbackup
# ./install.sh
```

ACTUAL RESULTS
After answer the wizard question I have the following output:
```
Zimbra User: zimbra
Zimbra Hostname: xxxxx.xxx.xx
Zimbra IP Address: XXX.XXX.XXX.XXX
Zimbra LDAP Password: xxxxxxxx
Zimbra Zmbackup Account: zmbackup@xxxxx.xxx.xx
Zimbra Zmbackup Password: MGU4ZmQ5ZjViZDg5NDJhMjM5Nzc5ZTMy
Zimbra Install Directory: /opt/zimbra
Zimbra Backup Directory: /media/backups
Zmbackup Install Directory: /usr/local/bin
Zmbackup Settings Directory: /etc/zmbackup
Zmbackup Backups Days Max: 30
Zmbackup Number of Threads: 3
Zmbackup Backup Lock: false
Zmbackup Session Default Type: SQLITE3

Installing dependencies. Please wait...
Dependencies installed with success!
Installing... Please wait while we made some changes.
ERROR - Can't create the user. Executing rollback process
Error description: ERROR: account.INVALID_PASSWORD (invalid password: not enough punctuation characters)
Removing... Please wait while we made some changes.

```

**Comment by lucascbeyeler** [comment]
Hello @guinuxbr,

The problem is because you are trying to use a password for Zmbackup account that your Zimbra consider not safe. Try to create your own and see if it works.

Regards,
Lucas Costa Beyeler

**Comment by guinuxbr** [comment]
I already have done this. My Zimbra is configured to accept a password with
10 characters at minimum, 1 capitalized, 1 number and 1 ponctual. I really
don't know what I have to do.

Em ter, 24 de abr de 2018 18:06, Lucas Costa Beyeler <
notifications@github.com> escreveu:

**Comment by pavanlinux** [comment]
Having CentOS 7.x and ZCS 8.8.15 OSE

[root@mail zmbackup]# ./install.sh
Loading installer - PLEASE WAIT
  Root Privileges...              [ROOT]
  Old Zmbackup Install...           Checking OS...                [RED HAT ENTERPRISE LINUX]
.......
Same issue when I followed the given steps:
Installing dependencies. Please wait...
Dependencies installed with success!
Installing... Please wait while we made some changes.
ERROR - Can't create the user. Executing rollback process
Error description: ERROR: account.INVALID_PASSWORD (invalid password: not enough punctuation characters)
Removing... Please wait while we made some changes.

**Comment by PandemiK911** [comment]
It seems install script does not read password from the invite. As a workaround, you can simply setup your password in the installScript/vars.sh file.
Do not forget to remove this file after install as it could be a security risk.

**Comment by guinuxbr** [comment]
As I'm not using Zimbra anymore, I'll close this issue.
By the way, I had no chance to test the @Azylog suggestion that seems to be viable.
Thank you guys anyway!
