### ISSUE TITLE
Zmbackup is not executing because of a error while trying to read the config file

### ISSUE THREAD

**Issue by lucascbeyeler** [lucascbeyeler/zmbackup#97]
##### ISSUE TYPE
- Bug Report

##### ENVIRONMENT VERSION
- Zmbackup Version: 1.2.2
- Zimbra Version: any
- Linux Distribution & Version: any

##### SUMMARY
For some reason Zmbackup is returning a lot of errors if you try to use the new release (1.2.2). The errors are the following:
```
$ zmbackup -l
You need to define the variable LDAPADMIN.
You need to define the variable LDAPPASS.
You need to define the variable ROTATE_TIME.
You need to define the variable SESSION_TYPE.
You need to define the variable BACKUP_INACTIVE_ACCOUNTS.
Some errors are found inside the config file. Please fix then and try again later.

```

**Comment by lucascbeyeler** [comment]
Won't Fix - Rewriting the entire Zmbackup instead

**Comment by rodrigomeneguet** [comment]
Good afternoon friend, I'm having the same problem, is there any way to fix it in version 1.2.2 or do we have to wait for version 1.2.3?

**Comment by ananiasfilho** [comment]
We have fixed and it will be available in next hours.
@rodrigomeneguet  - You can fix it using our FORK while @lucascbeyeler accept merge/pull request.
https://github.com/ananiasfilho/zmbackup

**Comment by lucascbeyeler** [comment]
Hello @rodrigomeneguet 

Could you try again using the branch 1.2-version? I included all the fixes proposed by @ananiasfilho.

Regards,
Lucas Costa Beyeler
