### ISSUE TITLE
Can't extract accounts from LDAP

### ISSUE THREAD

**Issue by rodrigomeneguet** [lucascbeyeler/zmbackup#98]
ISSUE TYPE
**Bug Report**

ENVIRONMENT VERSION
Zmbackup Version: **zmbackup-1.2.2**
Zimbra Version: **8.8.8**
Linux Distribution & Version: **Centos 7.4**

```
[zimbra@mail log]$ zmbackup -f
ERROR - Can't extract accounts from LDAP - See log for more information
Nothing to do. Closing...
```

```
[root@mail log]# tail messages`
May  8 15:24:22 mail root[18466]: Zmbackup: MAILHOST not informed - setting as 127.0.0.1 instead.
May  8 15:24:22 mail root[18471]: Zmbackup: EMAIL_SENDER not informed - setting as root@adress.com instead
May  8 15:24:22 mail root[18483]: Zmbackup: LDAP - Can't extract accounts from LDAP - Error below:
May  8 15:24:22 mail root[18484]: Zmbackup: ldap_sasl_bind(SIMPLE): Can't contact LDAP server (-1)
May  8 15:24:22 mail root[18508]: Zmbackup: Mail sended to mail@adress.com to notify about the backup routine conclusion.
May  8 15:24:22 mail root[18510]: Zmbackup: Excluding the temporary files before close.
```

**Comment by lucascbeyeler** [comment]
Hello @rodrigomeneguet 

This is not a bug.... it's looks like you don't have part of the variables inside the /etc/zmbackup/zmbackup.conf. Try recreate the file with all the fields with the correct values and try again.

Regards,
Lucas Costa Beyeler

**Comment by rodrigomeneguet** [comment]
Hello Lucas, really, the problem was in the variable LDAPSERVER, it was filled with 127.0.0.1, just change to the corresponding ip.
Thank you very much.

**Comment by lucascbeyeler** [comment]
Hello @rodrigomeneguet 

Good to know that your problem was solved. If you need anything just reopen this issue (if it is the same subject) or open a new one.

Regards,
Lucas Costa Beyeler

**Comment by diterdepaula** [comment]
Oi Lucas, estou com o mesmo problema acima, qual o formato que deve-se informar na linha ldap:
Simplesmente assim: LDAPSERVER=127.0.0.1
Ou assim: ldap://127.0.0.1:389
Valeu.

**Comment by diterdepaula** [comment]
Em tempo..

+ ERR='++ ldapsearch -x -H 127.0.0.1 -D uid=zimbra,cn=admins,cn=zimbra -w xxxxxxxxxx -b '\'''\'' -LLL '\''(objectclass=zimbraAccount)'\'' zimbraMailDeliveryAddress
Could not parse LDAP URI(s)=127.0.0.1 (3)'
+ echo 'ERROR - Can'\''t extract accounts from LDAP - See log for more information'

**Comment by rodrigomeneguet** [comment]
@diterdepaula amigo eu utilizei neste formato:

LDAPSERVER=ldap://127.0.0.1:389

Lembrando que o 127,0,0,1 deve ser substituído pelo ip da interface, foi assim que funcionou para mim.
