### ISSUE TITLE
Fresh install: Error: no such table: backup_account

### ISSUE THREAD

**Issue by MartinTerp** [lucascbeyeler/zmbackup#99]
##### ISSUE TYPE
- Bug Report

##### ENVIRONMENT VERSION
- Zmbackup Version: 1.2.2
- Zimbra Version: 8.8.8
- Linux Distribution & Version: CentOS7

##### SUMMARY

After installing, nothing happends, sqlite database not populated, eventhough i choose TXT

##### STEPS TO REPRODUCE

This is my first run ever, no backups made before this
```
[zimbra@mail01 ~]$ zmbackup -f
WARN: my@email.com already has backup today. Nothing to do.
Error: no such table: backup_account
.....
Nothing to do. Closing...
```

**Comment by AndreFelipeMachado** [comment]
Hello,
I tried editing /etc/zmbackup/zmbackup.conf
#AFM 20180522
#SESSION_TYPE=TXT
SESSION_TYPE=SQLITE3

then 
sudo su -
su - zimbra
zmbackup -m 
but the /opt/zimbra/backup/sessions.sqlite3 resulted empty.
Then manually executed
sqlite3 /opt/zimbra/backup/sessions.sqlite3 < /usr/local/lib/zmbackup/sqlite3/database.sql
and now it is created with its tables but still no data.
Situation improved, but still not getting a backup at a  test lab install:

zimbra@ubuntu1404ltsserver01:~$ zmbackup -f 
WARN: admin@zimbratest.com.br found inside blacklist - Nothing to do.
WARN: ham.9rb9jhqm@zimbratest.com.br found inside blacklist - Nothing to do.
WARN: spam.lcbuqph9an@zimbratest.com.br found inside blacklist - Nothing to do.
WARN: virus-quarantine._qcob9qp@zimbratest.com.br found inside blacklist - Nothing to do.
WARN: galsync.kv2vtfn_@zimbratest.com.br found inside blacklist - Nothing to do.
WARN: teste1@zimbratest.com.br already has backup today. Nothing to do.
WARN: teste2@zimbratest.com.br already has backup today. Nothing to do.
WARN: galsync@zimbratest2.com.br found inside blacklist - Nothing to do.
WARN: zmbackup@zimbratest.com.br found inside blacklist - Nothing to do.
Nothing to do. Closing...

Regards.

**Comment by the-solipsist** [comment]
Hi. I'm facing the same issue. Any suggested resolutions?

**Comment by digitalray** [comment]
Same here: Error: no such table: backup_account. Also it doesn't seem to keep a log in the config defined location which is /opt/zimbra/log/zmbackup.log. I'll try to uninstall and reinstall configured with sqlite and see if that works.

**Comment by digitalray** [comment]
Uninstalling and reinstalling with sqlite option did get rid of that error message. But now when I do a -f -a acct@domain.com, the generated archive file is 0 bytes. And /opt/zimbra/log/zmbackup.log again contains no log entries.

**Comment by mvldebian** [comment]
Same here,  https://groups.google.com/forum/#!topic/zmbackup/ba4dn9HUcGA

**Comment by ananiasfilho** [comment]
> Same here, https://groups.google.com/forum/#!topic/zmbackup/ba4dn9HUcGA

Try using new 1.2.3 branch!

**Comment by abdou84** [comment]
> Hello,
> I tried editing /etc/zmbackup/zmbackup.conf
> #AFM 20180522
> #SESSION_TYPE=TXT
> SESSION_TYPE=SQLITE3
> 
> then
> sudo su -
> su - zimbra
> zmbackup -m
> but the /opt/zimbra/backup/sessions.sqlite3 resulted empty.
> Then manually executed
> sqlite3 /opt/zimbra/backup/sessions.sqlite3 < /usr/local/lib/zmbackup/sqlite3/database.sql
> and now it is created with its tables but still no data.
> Situation improved, but still not getting a backup at a test lab install:
> 
> zimbra@ubuntu1404ltsserver01:~$ zmbackup -f
> WARN: [admin@zimbratest.com.br](mailto:admin@zimbratest.com.br) found inside blacklist - Nothing to do.
> WARN: [ham.9rb9jhqm@zimbratest.com.br](mailto:ham.9rb9jhqm@zimbratest.com.br) found inside blacklist - Nothing to do.
> WARN: [spam.lcbuqph9an@zimbratest.com.br](mailto:spam.lcbuqph9an@zimbratest.com.br) found inside blacklist - Nothing to do.
> WARN: virus-quarantine._[qcob9qp@zimbratest.com.br](mailto:qcob9qp@zimbratest.com.br) found inside blacklist - Nothing to do. WARN: galsync.kv2vtfn_@zimbratest.com.br found inside blacklist - Nothing to do.
> WARN: [teste1@zimbratest.com.br](mailto:teste1@zimbratest.com.br) already has backup today. Nothing to do.
> WARN: [teste2@zimbratest.com.br](mailto:teste2@zimbratest.com.br) already has backup today. Nothing to do.
> WARN: [galsync@zimbratest2.com.br](mailto:galsync@zimbratest2.com.br) found inside blacklist - Nothing to do.
> WARN: [zmbackup@zimbratest.com.br](mailto:zmbackup@zimbratest.com.br) found inside blacklist - Nothing to do.
> Nothing to do. Closing...
> 
> Regards.

go to vim /etc/zmbackup/blacklist.conf
remove all account from this file
save and quit
try zmbackup -f agin should work
